apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/app: fortune-teller
  name: fortune-teller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: fortune-teller
  name: fortune-service
  namespace: fortune-teller
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/app: fortune-teller
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/app: fortune-teller
  name: fortune-app
  namespace: fortune-teller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: fortune-teller
  strategy: {}
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-log-level: warn,linkerd2_proxy=info,h2=trace
        config.linkerd.io/proxy-version: ver-protocol-error-fix-1
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app.kubernetes.io/app: fortune-teller
    spec:
      containers:
      - env:
        - name: GODEBUG
          value: http2debug=2
        image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
        name: fortune-app
        ports:
        - containerPort: 50051
          name: grpc
        resources: {}
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-cluster
    kubernetes.io/ingress.class: grpc
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/configuration-snippet: |
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:50051;
      grpc_hide_header l5d-remote-ip;
      grpc_hide_header l5d-server-id;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/app: fortune-teller
  name: fortune-ingress
  namespace: fortune-teller
spec:
  rules:
  - host: fortune-teller.tree.outstandingwombat.com
    http:
      paths:
      - backend:
          serviceName: fortune-service
          servicePort: grpc
  tls:
  - hosts:
    - fortune-teller.tree.outstandingwombat.com
    secretName: fortune-teller.tree.outstandingwombat.com-tls
---
